include:
  - project: dke/apps/templates/job-templates
    #ref: develop
    file: job-templates.yml
  - project: nse/ci
    file:
      - /ci/lib/common.yml
      - /ci/jobs/build-package.yml
      - /ci/jobs/publish-package.yml

default:
  image: "python:3.8"

stages:
  - unit-test
  - lint-check
  - build
  - publish

build-package:
  rules:
    - when: on_success
publish-package:
  rules:
    - if: $CI_COMMIT_TAG

before_script:
  - pip install .[dev]

unit_test:
  stage: unit-test
  extends: .unit-tests
  variables:
   SRC_PROJECT: '$CI_PROJECT_PATH'
   TEST_FOLDER: 'tests'
   NEXUS_STAGING_TOKEN: '$NEXUS_STAGING_TOKEN'

lint_check:
  stage: lint-check
  extends: .flake8
  allow_failure: true
